export const categories = [
  {
    id: 1,
    title: "Sembako",
    labelColor: "bg-pink-200 text-pink-800",
    image: "/image2.jpeg",
  },
  {
    id: 2,
    title: "Alat Tulis",
    labelColor: "bg-purple-200 text-purple-800",
    image: "/image3.png",
  },
  {
    id: 3,
    title: "Rumah Tangga",
    labelColor: "bg-orange-200 text-orange-800",
    image: "/image4.jpeg",
  },
  {
    id: 4,
    title: "Bumbu Dapur",
    labelColor: "bg-blue-200 text-blue-800",
    image: "/image5.jpeg",
  },
  {
    id: 5,
    title: "Snack",
    labelColor: "bg-green-200 text-green-800",
    image: "/image6.jpeg",
  },
  {
    id: 6,
    title: "Minuman",
    labelColor: "bg-yellow-200 text-yellow-800",
    image: "/image7.jpeg",
  },
  {
    id: 7,
    title: "Mainan",
    labelColor: "bg-red-200 text-red-800",
    image: "/image9.jpeg",
  },
  {
    id: 8,
    title: "Obat-Obatan",
    labelColor: "bg-indigo-200 text-indigo-800",
    image: "/image8.jpeg",
  },
];

export const products = [
  {
    id: 1,
    categoryId: 1,
    title: "Beras Pandan Wangi 5kg",
    rating: 4.9,
    reviewCount: 112,
    priceOriginal: 85000,
    priceDiscount: 82000,
    image: "/image3.png",
  },
  {
    id: 2,
    categoryId: 2,
    title: "Pulpen Hitam Standar",
    rating: 4.7,
    reviewCount: 78,
    priceOriginal: 5000,
    priceDiscount: 4500,
    image: "/image3.png",
  },
  {
    id: 3,
    categoryId: 3,
    title: "Set Sapu dan Pengki",
    rating: 4.8,
    reviewCount: 95,
    priceOriginal: 30000,
    priceDiscount: 28500,
    image: "/image3.png",
  },
  {
    id: 4,
    categoryId: 4,
    title: "Bawang Putih Bubuk",
    rating: 4.6,
    reviewCount: 40,
    priceOriginal: 15000,
    priceDiscount: 13000,
    image: "/image3.png",
  },
  {
    id: 5,
    categoryId: 5,
    title: "Keripik Singkong Balado",
    rating: 4.9,
    reviewCount: 102,
    priceOriginal: 12000,
    priceDiscount: 10000,
    image: "/image3.png",
  },
  {
    id: 6,
    categoryId: 6,
    title: "Teh Botol Sosro 450ml",
    rating: 4.7,
    reviewCount: 90,
    priceOriginal: 5000,
    priceDiscount: 4500,
    image: "/image3.png",
  },
  {
    id: 7,
    categoryId: 7,
    title: "Mainan Balok Kayu Edukatif",
    rating: 4.8,
    reviewCount: 65,
    priceOriginal: 75000,
    priceDiscount: 70000,
    image: "/image3.png",
  },
  {
    id: 8,
    categoryId: 8,
    title: "Paracetamol 500mg (10 Tablet)",
    rating: 4.9,
    reviewCount: 110,
    priceOriginal: 10000,
    priceDiscount: 8500,
    image: "/image3.png",
  },
];

export const teamData = [
  {
    id: 1,
    name: "Richardo Mario Martin",
    description: "VIKINGS yang terdampar di pulau NUSANTARA",
    image: "/1.jpg",
    tags: ["photography", "travel", "winter"],
  },
  {
    id: 2,
    name: "Putu Cahya Purnama",
    description: "Seorang petarung barbarian asal skotlandia selatan",
    image: "/2.jpg",
    tags: ["hiking", "exploration", "nature"],
  },
  {
    id: 3,
    name: "Adrial Ignatius Andi Lolo",
    description: "Seorang komedian asal skotlandia selatan",
    image: "/3.jpg",
    tags: ["hiking", "exploration", "nature"],
  },
];

export const user = teamData.find((member) => member.id === 2);

export const transactions = [
  {
    id: 1,
    userId: 2,
    date: "2025-04-05",
    items: [
      { productId: 1, quantity: 1 },
      { productId: 5, quantity: 2 },
    ],
    total: 102000,
    status: "Selesai",
  },
  {
    id: 2,
    userId: 2,
    date: "2025-04-06",
    items: [
      { productId: 2, quantity: 3 },
      { productId: 4, quantity: 1 },
    ],
    total: 19500,
    status: "Selesai",
  },
  {
    id: 3,
    userId: 1,
    date: "2025-04-06",
    items: [{ productId: 6, quantity: 6 }],
    total: 27000,
    status: "Menunggu Pembayaran",
  },
];

export const inventory = [
  {
    id: 1,
    productsId: 1,
    stock: 50,
    minStock: 10,
    location: "Gudang A",
  },
  {
    id: 2,
    productsId: 2,
    stock: 200,
    minStock: 30,
    location: "Rak 1B",
  },
  {
    id: 3,
    productsId: 3,
    stock: 75,
    minStock: 15,
    location: "Gudang B",
  },
  {
    id: 4,
    productsId: 4,
    stock: 100,
    minStock: 20,
    location: "Rak 2A",
  },
  {
    id: 5,
    productsId: 5,
    stock: 80,
    minStock: 25,
    location: "Rak 3C",
  },
  {
    id: 6,
    productsId: 6,
    stock: 300,
    minStock: 50,
    location: "Rak 4D",
  },
  {
    id: 7,
    productsId: 7,
    stock: 40,
    minStock: 10,
    location: "Gudang C",
  },
  {
    id: 8,
    productsId: 8,
    stock: 150,
    minStock: 50,
    location: "Rak 5E",
  },
];
